server:
  port: 8090
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Gestióndeclientes
          uri: lb://Gestióndeclientes
          predicates:
            - Path=/api/Client/**
            - Path=/api/stateuser/**
        - id: GestióndekarymovMicroservices
          uri: lb://GestióndekarymovMicroservices
          predicates:
            - Path=/api/kardex/**
        - id: GestióndemontytarMicroservices
          uri: lb://GestióndemontytarMicroservices
          predicates:
            - Path=/api/AmountandRates/**
        - id: GestióndePréstyDevMicroservices
          uri: lb://pet-GestióndePréstyDevMicroservices
          predicates:
            - Path=/api/LoanTools/**
        - id: GestiónInvdeHerrMicroservices
          uri: lb://GestiónInvdeHerrMicroservices
          predicates:
            - Path=/api/Tools/**
            - Path=/api/statetools/**
        - id: ReportyconsMicroservices
          uri: lb://ReportyconsMicroservices
          predicates:
            - Path=/api/report/**
            - Path=/api/DataReport/**