server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: Gestiondeclientes
          uri: lb://GESTIONDECLIENTES
          predicates:
            - Path=/api/Client/**, /api/stateuser/**
        - id: GestiondekarymovMicroservices
          uri: lb://GESTIONDEKARYMOVMICROSERVICES
          predicates:
            - Path=/api/kardex/**
        - id: GestiondemontytarMicroservices
          uri: lb://GESTIONDEMONTYTARMICROSERVICES
          predicates:
            - Path=/api/AmountandRates/**
        - id: GestiondePrestyDevMicroservices
          uri: lb://GESTIONDEPRESTYDEVMICROSERVICES
          predicates:
            - Path=/api/LoanTools/**
        - id: GestionInvdeHerrMicroservices
          uri: lb://GESTIONINVDEHERRMICROSERVICES
          predicates:
            - Path=/api/Tools/**, /api/statetools/**
        - id: ReportyconsMicroservices
          uri: lb://REPORTYCONSMICROSERVICES
          predicates:
            - Path=/api/report/**, /api/DataReport/**