FROM eclipse-temurin:17-jdk
ARG JAR_FILE=target/GestióndemontytarMicroservices.jar
COPY ${JAR_FILE} GestióndemontytarMicroservices.jar
ENTRYPOINT ["java", "-jar", "/GestióndemontytarMicroservices.jar"]