pipeline {
    agent any
    stages{
        stage('Build Frontend'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/RojoMax12/ProyectoTingeso']])
                dir("ToolRentFrontend"){
                    bat "npm install" // Use 'bat' for Windows agents or 'sh' for Unix/Linux agents
                    bat "npm run build" // Use 'bat' for Windows agents or 'sh' for Unix/Linux agents
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("ToolRentFrontend"){
                    script{
                        withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t rojomax12/toolrent-frontend ."
                            bat "docker push rojomax12/toolrent-frontend"
                        }
                    }
                }
            }
        }
    }
}